WAD_Team4D/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import include
from upskill_photography import views

urlpatterns = [
    path('', include('upskill_photography.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

upskill_photography/urls.py
from django.urls import path
from upskill_photography import views
app_name = 'upskill_photography'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('faq/', views.faq, name='faq'),
    path('discovery/', views.discovery, name='discovery'),
    path('search/', views.search_result, name='search_result'),
    path('account/', views.account, name='account'),
    path('account/change_profile_picture/', views.change_profile_picture, name='change_profile_picture'),
    path('account/uploads/', views.uploads, name='uploads'),
    path('account/uploads/upload/', views.upload, name='upload'),
    path('categories/', views.categories, name='categories'),
    path('categories/<slug:category_name_slug>/', views.show_category, name='show_category'),
    path('user/<str:userprofile_username>/', views.userprofile, name='userprofile'),
    path('user/<str:userprofile_username>/<uuid:picture_id>/', views.picture_view, name='picture_view'),
    
    # Url's used by AJAX requests
    path('like_picture/', views.LikePictureView.as_view(), name='like_picture'),
    path('remove_comment/', views.RemoveCommentView.as_view(), name='remove_comment'),
    path('remove_picture/', views.RemovePictureView.as_view(), name='remove_picture'),
]

upskill_photography/models.py
from django.contrib.auth.models import User
from django.core.files.base import ContentFile
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.template.defaultfilters import slugify
from io import BytesIO
import os
from PIL import Image
import uuid


## Private Method - Rename the UserProfile profile picture on creation ##
# Taken from https://stackoverflow.com/questions/15140942/django-imagefield-change-file-name-on-upload
def rename_profile_picture(instance, filename):
    upload_to="profile_images"
    ext = filename.split('.')[-1]
    filename = '{}.{}'.format(uuid.uuid4().hex, ext)
    return os.path.join(upload_to, filename)


## Signal - Every time a new User is created, a corresponding UserProfile is created ##
@receiver(post_save, sender=User)
def update_profile_signal(sender, instance, created, **kwargs):
    if created:     
        UserProfile.objects.create(user=instance)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    profile_picture = models.ImageField(upload_to='profile_images', blank=True)
    
    def save(self, *args, **kwargs):
        if self.profile_picture:
            if not self.make_thumbnail():
                raise Exception('Could not create thumbnail - is the file type valid?')
        super(UserProfile, self).save(*args, **kwargs)
    
    ## Private Method - Scales down and crops the profile picture on upload ##
    # Taken from https://stackoverflow.com/questions/23922289/django-pil-save-thumbnail-version-right-when-image-is-uploaded
    def make_thumbnail(self):
        image = Image.open(self.profile_picture)
        width, height = image.size
        if width > height:
            new_width = height
            new_height = height
        else:
            new_width = width
            new_height = width
        # Crop the image to a centered square
        image = image.crop(box=((width - new_width)//2, (height - new_height)//2, (width + new_width)//2, (height + new_height)//2))
        image.thumbnail((480,480), Image.ANTIALIAS)
        thumb_name, thumb_extension = os.path.splitext(self.profile_picture.name)
        thumb_extension = thumb_extension.lower()
        thumb_filename = thumb_name + '_thumb' + thumb_extension
        if thumb_extension in ['.jpg', '.jpeg']:
            FTYPE = 'JPEG'
        elif thumb_extension == '.gif':
            FTYPE = 'GIF'
        elif thumb_extension == '.png':
            FTYPE = 'PNG'
        else:
            return False    # Unrecognized file type
        # Save thumbnail to in-memory file as StringIO
        temp_thumb = BytesIO()
        image.save(temp_thumb, FTYPE)
        temp_thumb.seek(0)
        # set save=False, otherwise it will run in an infinite loop
        self.profile_picture.save(thumb_filename, ContentFile(temp_thumb.read()), save=False)
        temp_thumb.close()
        return True
    
    def __str__(self):
        return f'{self.user.username}'


## Returns the hex representation of a uuid4 ##
def uuid4_hex():
    return uuid.uuid4().hex

## Private Method - Renames The image on upload ##
# Taken from https://stackoverflow.com/questions/15140942/django-imagefield-change-file-name-on-upload
def rename_image(instance, filename):
    upload_to = "user_uploads"
    ext = filename.split('.')[-1]
    filename = '{}.{}'.format(uuid.uuid4().hex, ext)
    return os.path.join(upload_to, filename)

## Private Method - Renames The thumbnail on upload ##
# Taken from https://stackoverflow.com/questions/15140942/django-imagefield-change-file-name-on-upload
def rename_thumbnail(instance, filename):
    upload_to="user_uploads_thumbnails"
    ext = filename.split('.')[-1]
    filename = '{}-thumb.{}'.format(uuid.uuid4().hex, ext)
    return os.path.join(upload_to, filename)

class Picture(models.Model):
    uploading_user = models.ForeignKey('UserProfile', on_delete=models.CASCADE)
    picture_id = models.UUIDField(primary_key=True, default=uuid4_hex, editable=False)
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to=rename_image)
    thumbnail = models.ImageField(upload_to=rename_thumbnail, blank=True, null=True, default=None, editable=False)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    latitude = models.DecimalField(max_digits=8, decimal_places=5, blank=True, null=True, default=None)
    longitude = models.DecimalField(max_digits=8, decimal_places=5, blank=True, null=True, default=None)
    timestamp = models.DateTimeField(auto_now_add=True)
    likes = models.PositiveIntegerField(default=0)
    views = models.PositiveIntegerField(default=0)
    
    def save(self, *args, **kwargs):
        if self.likes < 0:
            self.likes = 0
        if self.views < 0:
            self.views = 0
        if self.latitude:
            if self.latitude < -90:
                self.latitude = -90
            if self.latitude > 90:
                self.latitude = 90
        if self.longitude:
            if self.longitude < -180:
                self.longitude = -180
            if self.longitude > 180:
                self.longitude = 180
        if not self.thumbnail:
            if self.image and not self.make_thumbnail():
                raise Exception('Could not create thumbnail - is the file type valid?')
        super(Picture, self).save(*args, **kwargs)
    
    ## Private Method - Creates the thumbnail from the uploaded image and adds padding to make it square ##
    # Taken from https://stackoverflow.com/questions/23922289/django-pil-save-thumbnail-version-right-when-image-is-uploaded
    def make_thumbnail(self):
        unpadded_image = Image.open(self.image)
        unpadded_image = unpadded_image.copy()
        unpadded_image.thumbnail((480,480), Image.ANTIALIAS)
        width, height = unpadded_image.size
        image = Image.new("RGB", (480, 480))
        image.paste(unpadded_image, box=((480-width)//2, (480-height)//2, (480-width)//2 + width, (480-height)//2 + height))
        thumb_name, thumb_extension = os.path.splitext(self.image.name)
        thumb_extension = thumb_extension.lower()
        thumb_filename = thumb_name + '_thumb' + thumb_extension
        if thumb_extension in ['.jpg', '.jpeg']:
            FTYPE = 'JPEG'
        elif thumb_extension == '.gif':
            FTYPE = 'GIF'
        elif thumb_extension == '.png':
            FTYPE = 'PNG'
        else:
            return False    # Unrecognized file type
        # Save thumbnail to in-memory file as StringIO
        temp_thumb = BytesIO()
        image.save(temp_thumb, FTYPE)
        temp_thumb.seek(0)
        # set save=False, otherwise it will run in an infinite loop
        self.thumbnail.save(thumb_filename, ContentFile(temp_thumb.read()), save=False)
        temp_thumb.close()
        return True
    
    
    def __str__(self):
        return str(self.uploading_user.user.username) + " - " + str(self.title)

 

class Comment(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    picture = models.ForeignKey('Picture', on_delete=models.CASCADE)
    user = models.ForeignKey('UserProfile', on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    text = models.TextField()
    
    def __str__(self):
        return str(self.id) + " - " + str(self.text)



class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(unique=True, editable=False)
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)
    
    def __str__(self):
        return str(self.name)

upskill_photography/forms.py
from django import forms
from upskill_photography.models import Picture, UserProfile


class PictureUploadForm(forms.ModelForm):
    class Meta:
        model = Picture
        fields = ('title', 'image', 'category')


class ProfilePictureForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('profile_picture',)

templates/upskill_photography/account.html
{% extends 'upskill_photography/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Your Account
{% endblock %}

{% block body_block %}
	<div class="bg-dark px-4 pb-4">
	<p><a href="{% url 'upskill_photography:userprofile' user.username %}" class="btn btn-outline-light p-2">Back to Profile</a></p>
	<hr class="border-light">
	<p class="text-light"><strong>Account and Settings</strong></p>
	<p><a href="{% url 'auth_password_change' %}" class="btn btn-outline-light p-2">Change Password</a></p>
	<p><a href="{% url 'upskill_photography:change_profile_picture' %}" class="btn btn-outline-light p-2">Change Profile Picture</a></p>
	<p><a href="{% url 'upskill_photography:uploads' %}" class="btn btn-outline-light p-2">View Uploads</a></p>
	<p><a href="{% url 'upskill_photography:upload' %}" class="btn btn-outline-light">Upload a Picture</a></p>
	</div>
{% endblock %}

templates/upskill_photography/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load upskill_photography_template_tags %}

<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta name="description" content="Photo sharing website for hobby photographers">
		<meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
		<meta name="generator" content="Jekyll v3.8.5">
		<link rel="icon" href="{% static 'images/favicon.ico' %}">
		<title>
			{% block title_block %}{% endblock %} - Upskill Photography
		</title>
		
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
		<link href="https://api.mapbox.com/mapbox-gl-js/v2.2.0/mapbox-gl.css" rel="stylesheet">
		<link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.7.0/mapbox-gl-geocoder.css" type="text/css">
	</head>
	
	<body>
		<header>
			<nav class="navbar navbar-expand-md navbar-dark static-top bg-dark p-0">
				<a class="navbar-brand p-2" href="{% url 'upskill_photography:index' %}">Upskill Photography</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				
				<div class="collapse navbar-collapse flex-column" id="navbarCollapse">
					<form class="form-inline mr-auto" action="{% url 'upskill_photography:search_result' %}" method="post">
						{% csrf_token %}
						<input class="form-control mr-sm-2" type="search" name="search_query" placeholder="Search" aria-label="Search">
						<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
					</form>
					<ul class="navbar-nav mr-auto">
						<li class="nav-item"><a class="nav-link" href="{% url 'upskill_photography:index' %}">Home</a></li>
						<li class="nav-item"><a class="nav-link" href="{% url 'upskill_photography:discovery' %}">Discovery</a></li>
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" href="{% url 'upskill_photography:categories' %}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								Categories
							</a>
							<div class="dropdown-menu" aria-labelledby="navbarDropdown">
								<a class="dropdown-item" href="{% url 'upskill_photography:categories' %}">All Categories</a>
								{% if categories %}
								{% for category in categories %}
								<a class="dropdown-item" href="{% url 'upskill_photography:show_category' category.slug %}">{{ category.name }}</a>
								{% endfor %}
								{% endif %}
							</div>
						</li>
						{% if user.is_authenticated %}
						<li class="nav-item"><a class="nav-link" href="{% url 'upskill_photography:upload' %}">Upload a Picture</a></li>
						{% endif %}
					</ul>
				</div>
				<div class="w-20 mx-auto px-4">
					<ul class="list-group list-group-flush bg-transparent" style="list-style-type:none">
						{% if user.is_authenticated %}
						<li><a class="list-group-item list-group-item-action bg-transparent text-light" href="{% url 'upskill_photography:userprofile' user.username %}">{{ user.username }}</a></li>
						<li><a class="list-group-item list-group-item-action bg-transparent text-light" href="{% url 'auth_logout' %}?next=/">Logout</a></li>
						{% else %}
						<li><a class="list-group-item list-group-item-action bg-transparent text-light" href="{% url 'registration_register' %}">Register</a></li>
						<li><a class="list-group-item list-group-item-action bg-transparent text-light" href="{% url 'auth_login' %}">Login</a></li>
						{% endif %}
					</ul>
				</div>
			</nav>
		</header>
		
		<div class="container=fluid">
			<div class="row">
				<main role="main" class="w-75 mx-auto pb-4">
					{% block body_block %}{% endblock %}
				</main>
			</div>
			<div class="row">
				<footer class="w-100 mx-auto bg-dark">
					<div class="w-75 mx-auto">
						<p class="float-right"><a class="text-light px-4" href="#">Back To Top</a></p>
						<p>
							<a class="text-light px-4" href="{% url 'upskill_photography:faq' %}">FAQ</a><br>
							<a class="text-light px-4" href="{% url 'upskill_photography:contact' %}">Contact Us</a><br>
							<a class="text-light px-4" href="{% url 'upskill_photography:about' %}">About</a>
						</p>
					</div>
				</footer>
			</div>
		</div>
		
		<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" type="text/javascript" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js" type="text/javascript"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" type="text/javascript" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" type="text/javascript" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
		<script src='https://api.mapbox.com/mapbox-gl-js/v2.2.0/mapbox-gl.js' type="text/javascript"></script>
		<script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.7.0/mapbox-gl-geocoder.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.auto.min.js"></script>
		<script src="{% static "js/upskill_photography-ajax.js" %}" type="text/javascript" crossorigin="anonymous"></script>
		<script src="{% static "js/upskill_photography-mapBox.js" %}" type="text/javascript" crossorigin="anonymous"></script>
	</body>
	
</html>

templates/upskill_photography/index.html
{% extends 'upskill_photography/base.html' %}
{% load staticfiles %}

{% block title_block %}
   Home
{% endblock %}

{% block body_block %}
{% if first_picture %}
<div class="w-75 mx-auto m-4">
	<h2 class="text-center"><strong>Our Best Pictures</strong></h2>
	<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
		<ol class="carousel-indicators">
			<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
			{% for i in counter %}
			<li data-target="#carouselExampleIndicators" data-slide-to="{{ i }}"></li>
			{% endfor %}
		</ol>
		
		<div class="carousel-inner rounded">
			<div class="carousel-item active" style="max-height: 80vh;">
				<a class="d-flex align-items-center justify-content-center" href="{% url 'upskill_photography:picture_view' first_picture.uploading_user.user.username first_picture.picture_id %}">
					<img class="mw-100" src="{{ first_picture.image.url }}" alt="{{ first_picture.title }}" style="max-height: 75vh;">
				</a>
				<div class="carousel-caption d-none d-md-block">
					<a href="{% url 'upskill_photography:userprofile' first_picture.uploading_user.user.username %}">
						<h5 class="text-dark" style="text-shadow: 1px 1px #ffffff"><strong>{{ first_picture.uploading_user.user.username }}</strong></h5>
					</a>
					<p class="text-dark" style="text-shadow: 1px 1px #ffffff"><strong>{{ first_picture.title }}</strong></p>
				</div>
			</div>
			{% for picture in pictures %}
			<div class="carousel-item" style="max-height: 80vh;">
				<a class="d-flex align-items-center justify-content-center" href="{% url 'upskill_photography:picture_view' picture.uploading_user.user.username picture.picture_id %}">
					<img class="mw-100" src="{{ picture.image.url }}" alt="{{ picture.title }}" style="max-height: 75vh;">
				</a>
				<div class="carousel-caption d-none d-md-block">
					<a href="{% url 'upskill_photography:userprofile' picture.uploading_user.user.username %}">
						<h5 class="text-dark" style="text-shadow: 1px 1px #ffffff"><strong>{{ picture.uploading_user.user.username }}</strong></h5>
					</a>
					<p class="text-dark" style="text-shadow: 1px 1px #ffffff"><strong>{{ picture.title }}</strong></p>
				</div>
			</div>
			{% endfor %}
		</div>
	</div>
	<p><a href="{% url 'upskill_photography:discovery' %}" class="text-dark"><h4 class="text-center"><strong>Discover More Pictures</strong></h4></a></p>
</div>
{% else %}
	<h2>OOPS</h2>
	<h3>It looks likes there are no pictures so far</h3>
	{% if user.is_authenticated %}
	<h3>Why don't you make the first move and <a href="{% url 'upskill_photography:upload' %}">Upload</a> your first picture?</h3>
	{% else %}
	<h3><a href="{% url 'registration_register' %}">Register Here</a> and upload your first pictures</h3>
	{% endif %}
{% endif %}
{% endblock %}

templates/upskill_photography/picture_thumbnail.html
{% load staticfiles %}

<div class="col-xl-2 col-lg-3 col-md-4 col-sm-6 col-xs-12 mh-25">
	<a class="img-wrapper" href="{% url 'upskill_photography:picture_view' picture.uploading_user.user.username picture.picture_id %}">
		<img src="{{ picture.thumbnail.url }}" class="img-thumbnail img-responsive rounded" alt="{{ picture.title }}">
	</a>
	<div class="font-italic text-nowrap overflow-hidden">{{ picture.title }}</div>
	<div class="text-nowrap overflow-hidden">
		<a href="{% url 'upskill_photography:userprofile' picture.uploading_user.user.username %}" style="color: black"><span>{{ picture.uploading_user.user.username }}</span></a>
		<div class="float-right">
			{{ picture.views }}
			<img src="{% static 'images/view.ico' %}" alt="Views Icon" width="16" height="16">
		</div><br>
		<a href="{% url 'upskill_photography:show_category' picture.category.slug %}" style="color: black"><span>{{ picture.category.name }}</span></a>
		<div class="float-right">
			{{ picture.likes }}
			<img src="{% static 'images/like_blank.ico' %}" alt="Empty Like Icon" width="16" height="16">
		</div><br>
		<span>{{ picture.timestamp | date:"F d Y" }}</span><br>
		{% if picture.latitude %}
		{% if picture.longitude %}
		<span class="text-muted">Location Available</span>
		{% endif %}
		{% endif %}
	</div>
</div>

templates/upskill_photography/upload.html
{% extends 'upskill_photography/base.html' %}
{% load staticfiles %}

{% block title_block %}
Picture Upload
{% endblock %}

{% block body_block %}
<!--<h2> Upload a Picture</h2>
<form method="post" enctype="multipart/form-data" class="p-4">
  {% csrf_token %}
  <input type=
  <input type="file" name="image" accept="image/*" id="id_image">
  <button type="submit" class="btn btn-primary">Change Profile Picture</button>
</form>-->
<!--<a class="btn btn-danger" action="{% url 'upskill_photography:userprofile' user.username %}">Cancel</a>-->
<form method="post" enctype="multipart/form-data" class="p-4">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="checkbox" id="map-checkbox" name="use_location" value="true">
	<label for="map-checkbox"> Set Image Location (Optional)</label><br>
	<div id="map-container" data-set-location="true"></div>
	<input id="lat-input" type="hidden" name="latitude" value="">
	<input id="lng-input" type="hidden" name="longitude" value="">
	<button type="submit" class="btn btn-primary">Upload</button>
</form>
<a class="btn btn-danger" href="{% url 'upskill_photography:index' %}">Cancel</a>
{% endblock %}

templates/upskill_photography/user_profile.html
{% extends 'upskill_photography/base.html' %}
{% load staticfiles %}
{% load upskill_photography_template_tags %}

{% block title_block %}
      {% if userprofile %}
	  {{ userprofile.user.username }}
	  {% else %}
	  Invalid Username
	  {% endif %}
{% endblock %}

{% block body_block %}
	{% if userprofile %}
	<div class="bg-dark rounded-bottom">
		<div class="row">
			<div class="col-2">
				<div class="p-4">
				{% if userprofile.profile_picture %}
				<img src="{{ userprofile.profile_picture.url }}" class="img-thumbnail" style="border-radius:50%; border:solid black 2px; background-color: DimGray;" alt="{{ userprofile.user.username }} profile picture">
				{% else %}
				<img src="{% static 'images/unknown-user.png' %}" class="img-thumbnail" style="border-radius:50%; border:solid black 2px; background-color: DimGray;" alt="{{ userprofile.user.username }} profile picture">
				{% endif %}
				{% if userprofile.user == user %}
				<div class="p-2 text-center">
					<a href="{% url 'upskill_photography:change_profile_picture' %}" class="btn btn-sm btn-outline-light">{% if userprofile.profile_picture %}Change Profile Picture{% else %}Add Profile Picture{% endif %}</a>
				</div>
				{% endif %}
				</div>
			</div>
			<div class="col-1"></div>
			<div class="col-7">
				<table class="table-sm">
				  <tbody>
					<tr>
					  <th scope="row"><span class="text-light">Username:</span></th>
					  <td><span class="text-light">{{ userprofile.user.username }}</span></td>
					</tr>
					<tr>
					  <th scope="row"><span class="text-light">Member Since:</span></th>
					  <td><span class="text-light">{{ userprofile.user.date_joined | date:"F d Y" }}</span></td>
					</tr>
					<tr>
					  <th scope="row"><span class="text-light">Total Views:</span></th>
					  <td><span class="text-light">{{ total_views }}</span></td>
					</tr>
					<tr>
					  <th scope="row"><span class="text-light">Total Likes:</span></th>
					  <td><span class="text-light">{{ total_likes }}</span></td>
					</tr>
					<tr>
					  <th scope="row"><span class="text-light">Total Comments Received:</span></th>
					  <td><span class="text-light">{{ comments_received }}</span></td>
					</tr>
					<tr>
					  <th scope="row"><span class="text-light">Total Comments Created:</span></th>
					  <td><span class="text-light">{{ comments_created }}</span></td>
					</tr>
				  </tbody>
				</table>
			</div>
			{% if userprofile.user == user %}
			<div class="col-2">
				<p><a href="{% url 'upskill_photography:account' %}" class="btn btn-outline-light p-2">Account</a></p>
				<p><a href="{% url 'upskill_photography:uploads' %}" class="btn btn-outline-light p-2">View Uploads</a></p>
			</div>
			{% endif %}
		</div>
		<hr class="border-light" style="width: 99%;">
		{% if pictures %}
		<div class="d-flex">
			<div class="px-4">
				<p class="float-left text-light"><strong>Pictures By {{ userprofile.user.username }}</strong></p>
			</div>
			
			<form class="ml-auto px-4 text-light" action="{% url 'upskill_photography:userprofile' userprofile.user.username %}" method="post">
				{% csrf_token %}
				Sort By: 
				<select class="form-select bg-dark text-light" aria-label="Sorting Style" name="sort_style">
					<option value="new" {% if sort_style == 'new' %}selected{% endif %}>Upload Time</option>
					<option value="views" {% if sort_style == 'views' %}selected{% endif %}>Views</option>
					<option value="likes" {% if sort_style == 'likes' %}selected{% endif %}>Likes</option>
					<option value="comments" {% if sort_style == 'comments' %}selected{% endif %}>Comments</option>
				</select>
				<select class="form-select bg-dark text-light" aria-label="Sorting Order" name="sort_order">
					<option value="desc" {% if sort_order == 'desc' %}selected{% endif %}>Descending</option>
					<option value="asc" {% if sort_order == 'asc' %}selected{% endif %}>Ascending</option>
				</select>
				<button class="bg-transparent btn-outline-success" type="submit">Reload</button>
			</form>
		</div>
		{% else %}
		<p class="text-light p-4">{{ userprofile.user.username }} has not uploaded any pictures yet.</p>
		{% endif %}
	</div>
	{% if pictures %}
	<div class="row imagetiles">
		{% for picture in pictures %}
			{% get_picture_thumbnail picture %}
		{% endfor %}
	</div>
	{% endif %}
	{% else %}
	The user does not exist
	{% endif %}
{% endblock %}